#!/bin/bash

mkdir -p logs

USER=$(whoami)
HOST=$(hostname)
DATE=$(date "+%Y-%m-%d_%H-%M-%S")

LOG="logs/report_$DATE.txt"

echo "===== System Monitoring Report =====" > $LOG
echo "Generated by: $USER@$HOST on $(date)" >> $LOG
echo "" >> $LOG


# CPU PERFORMANCE
echo ">> CPU Performance (mpstat):" >> $LOG
mpstat 1 3 >> $LOG
echo "" >> $LOG


# CPU TEMPERATURE
# echo ">> CPU Temperature (sensors):"
# if command -v sensors &> /dev/null; then
#    sensors 2>/dev/null || echo "   [CPU temperature data not available in this environment]"
# else
#    echo "   [sensors command not found]"
# fi


# GPU UTILIZATION AND HEALTH
echo ">> GPU Info (nvidia-smi):" >> $LOG
if command -v nvidia-smi &> /dev/null
then
    nvidia-smi >> $LOG
else
    echo "No NVIDIA GPU detected or 'nvidia-smi' not available." >> $LOG
fi
echo "" >> $LOG

# DISK USAGE
echo ">> Disk Usage (df -h):" >> $LOG
df -h >> $LOG
echo "" >> $LOG

# DISK SMART STATUS
echo ">> Disk SMART Status (smartctl):" >> $LOG
if command -v smartctl &> /dev/null
then
    sudo smartctl -H /dev/sda >> $LOG 2>> $LOG || echo "SMART data not available (may be running under WSL or no disk access)" >> $LOG
else
    echo "Command 'smartctl' not found." >> $LOG
fi
echo "" >> $LOG

# MEMORY CONSUMPTION
echo ">> Memory Consumption (free -h):" >> $LOG
free -h >> $LOG
echo "" >> $LOG


# NETWORK INTERFACE STATISTICS
echo ">> Network Interfaces (ip -s link):" >> $LOG
ip -s link >> $LOG
echo "" >> $LOG

echo ">> Active Network Interfaces:" >> $LOG
ip addr show up | grep -E "^[0-9]+:|inet " >> $LOG
echo "" >> $LOG


# ALERT SYSTEM

echo ">> ALERTS:" >> $LOG

# CPU Alert
CPU_IDLE=$(mpstat 1 1 | awk '/Average/ && $12 ~ /[0-9.]+/ { print $12 }')
CPU_USAGE=$(echo "100 - $CPU_IDLE" | bc)

if (( $(echo "$CPU_USAGE > 80" | bc -l) )); then
  echo "⚠️  High CPU Usage: $CPU_USAGE%" >> $LOG
else
  echo "✅ CPU Usage Normal: $CPU_USAGE%" >> $LOG
fi

# RAM Alert
USED_MEM=$(free | awk '/Mem:/ { print $3 }')
TOTAL_MEM=$(free | awk '/Mem:/ { print $2 }')
RAM_PERCENT=$(echo "$USED_MEM / $TOTAL_MEM * 100" | bc -l)

if (( $(echo "$RAM_PERCENT > 90" | bc -l) )); then
  echo "⚠️  High RAM Usage: ${RAM_PERCENT}%" >> $LOG
else
  echo "✅ RAM Usage Normal: ${RAM_PERCENT}%" >> $LOG
fi

echo "" >> $LOG


disk_usage=$(df / | awk 'NR==2 {print $5}' | tr -d '%')

if (( disk_usage > 90 )); then
  echo "⚠️ ALERT: High Disk Usage: ${disk_usage}%"
fi

if [ -f /sys/class/thermal/thermal_zone0/temp ]; then
    temp_raw=$(cat /sys/class/thermal/thermal_zone0/temp)
    temp_c=$(echo "scale=1; $temp_raw / 1000" | bc)
    echo ">> CPU Temperature (thermal_zone0): $temp_c °C"

    if (( $(echo "$temp_c > 70" | bc -l) )); then
        echo "🔥 ALERT: CPU Temperature is high: ${temp_c}°C"
    fi
else
    echo "⚠️ Temperature info not available on this system."
fi


INFLUX_URL="http://localhost:8086/write?db=system_monitoring"
DATA="USED_MEM value=$USED_MEM"

curl -i -X POST "$INFLUX_URL" \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --data-binary "$DATA"



# -------------------------------
# SYSTEM LOAD METRICS
# -------------------------------
echo ">> System Load (uptime):" >> $LOG
uptime >> $LOG
echo "" >> $LOG

echo ">> Load Averages (/proc/loadavg):" >> $LOG
cat /proc/loadavg >> $LOG
echo "" >> $LOG
